</font>
      BOTTOMBAR
      </td>
    </tr>
  </table>
</td>
</tr>
</table>


<tr align=left valign=top><td>
  <img alt="" src="graphics/blank.gif" height="20">
</td></tr>


<table bgcolor="DARKBLUE" border=0 cellspacing=0 cellpadding=1 width="100%" >
  <tr><td>
  <table bgcolor="OFFWHITE" border=0 cellspacing=0 cellpadding=10 width="100%" >
    <tr><td>
    <table bgcolor="OFFWHITE" border=0 cellspacing=0 cellpadding=0 width="100%" >
    <tr valign=top>
      <td align=left>
        <font face="Helvetica" size="-1">
        Copyright &#169; <a href="mailto:gary.flake AT usa.net">Gary
        William Flake</a>, 1998-2002. All Rights Reserved.
        </font>
      </td>
      <td align=center>
        <img alt="" src="graphics/blank.gif" width=1 height=1>
      </td>
      <td align=right>
      <font face="Helvetica" size="-1">
        Last modified: MODDATE
      </font>
      </td>
    </tr>
    </table>
    </td></tr>
  </table>
  </td></tr>
</table>



</body>
</html>
