<p>
BOXBEG
<b>L-System Fractals</b>
BOXMID
<table align=center border=0 cellspacing=0 cellpadding=0 width="100%">
<tr align=center><td>
<table align=center border=0 cellspacing=2 cellpadding=0>
<tr align=center><td>
<a href="graphics/figa1.gif"><img alt="image" src="graphics/thumbfiga1.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figa2.gif"><img alt="image" src="graphics/thumbfiga2.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figa3.gif"><img alt="image" src="graphics/thumbfiga3.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figa4.gif"><img alt="image" src="graphics/thumbfiga4.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figa5.gif"><img alt="image" src="graphics/thumbfiga5.gif" width="60" height="60"></a>
</td></tr>
<tr align=center><td>
<a href="graphics/figa6.gif"><img alt="image" src="graphics/thumbfiga6.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figa7.gif"><img alt="image" src="graphics/thumbfiga7.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figa8.gif"><img alt="image" src="graphics/thumbfiga8.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figa9.gif"><img alt="image" src="graphics/thumbfiga9.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figa10.gif"><img alt="image" src="graphics/thumbfiga10.gif" width="60" height="60"></a>
</td></tr></table>
</td></tr></table>
BOXEND
<p>

BOXBEG
<b>IFS and MRCM Fractals</b>
BOXMID
<table align=center border=0 cellspacing=0 cellpadding=0 width="100%">
<tr align=center><td>
<table align=center border=0 cellspacing=2 cellpadding=0>
<tr align=center><td>
<a href="graphics/figb1.gif"><img alt="image" src="graphics/thumbfigb1.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figb2.gif"><img alt="image" src="graphics/thumbfigb2.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figb3.gif"><img alt="image" src="graphics/thumbfigb3.gif" width="60" height="60"></a>
</td></tr></table>
</td></tr><tr align=center><td>
<table align=center border=0 cellspacing=2 cellpadding=0>
<tr align=center><td>
<a href="graphics/figb4.gif"><img alt="image" src="graphics/thumbfigb4.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figb5.gif"><img alt="image" src="graphics/thumbfigb5.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figb6.gif"><img alt="image" src="graphics/thumbfigb6.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figb7.gif"><img alt="image" src="graphics/thumbfigb7.gif" width="60" height="60"></a>
</td></tr></table>
</td></tr></table>
BOXEND
<p>

BOXBEG
<b>Mandelbrot and Julia Set Fractals</b>
BOXMID
<table align=center border=0 cellspacing=0 cellpadding=0 width="100%">
<tr align=center><td>
<table align=center border=0 cellspacing=2 cellpadding=0>
<tr align=center><td>
<a href="graphics/figc1.jpg"><img alt="image" src="graphics/thumbfigc1.gif" width="80" height="60"></a>
</td><td>
<a href="graphics/figc2.jpg"><img alt="image" src="graphics/thumbfigc2.gif" width="80" height="60"></a>
</td><td>
<a href="graphics/figc3.jpg"><img alt="image" src="graphics/thumbfigc3.gif" width="80" height="60"></a>
</td><td>
<a href="graphics/figc4.jpg"><img alt="image" src="graphics/thumbfigc4.gif" width="80" height="60"></a>
</td></tr></table>
</td></tr></table>
BOXEND
<p>

BOXBEG
<b>Chaotic Dynamics</b>
BOXMID
<table align=center border=0 cellspacing=0 cellpadding=0 width="100%">
<tr align=center><td>
<table align=center border=0 cellspacing=2 cellpadding=0>
<tr align=center><td>
<a href="graphics/figd1.gif"><img alt="image" src="graphics/thumbfigd1.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figd2.gif"><img alt="image" src="graphics/thumbfigd2.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figd3.gif"><img alt="image" src="graphics/thumbfigd3.gif" width="60" height="60"></a>
</td></tr></table>
</td></tr><tr align=center><td>
<table align=center border=0 cellspacing=2 cellpadding=0>
<tr align=center><td>
<a href="graphics/figd4.gif"><img alt="image" src="graphics/thumbfigd4.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figd5.gif"><img alt="image" src="graphics/thumbfigd5.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figd6.gif"><img alt="image" src="graphics/thumbfigd6.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/figd7.gif"><img alt="image" src="graphics/thumbfigd7.gif" width="60" height="60"></a>
</td></tr></table>
</td></tr></table>
BOXEND
<p>

BOXBEG
<b>Complex Systems</b>
BOXMID
<table align=center border=0 cellspacing=0 cellpadding=0 width="100%">
<tr align=center><td>
<table align=center border=0 cellspacing=2 cellpadding=0>
<tr align=center><td>
<a href="graphics/fige1.gif"><img alt="image" src="graphics/thumbfige1.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/fige2.gif"><img alt="image" src="graphics/thumbfige2.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/fige3.gif"><img alt="image" src="graphics/thumbfige3.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/fige4.gif"><img alt="image" src="graphics/thumbfige4.gif" width="60" height="60"></a>
</td><td>
<a href="graphics/fige5.gif"><img alt="image" src="graphics/thumbfige5.gif" width="60" height="60"></a>
</td></tr></table>
</td></tr></table>
BOXEND