#define LEFT_COL_WIDTH 125
#define GAP_WIDTH       35

#define COLUMN_FONT face="Helvetica" size="-1"
#define MTITLEFONT face="Helvetica" size="-1"

#define OFFWHITE #f0f0f0
#define BLUE #bbbbdd
#define DARKBLUE #222255

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"
"http://www.w3.org/TR/REC-html40/loose.dtd"> 

<html>
<head>
<meta name="description" content="The Computational Beauty of Nature -
Computer Explorations of Fractals, Chaos, Complex Systems, and
Adaptation">
<meta name="keywords" content="computation, fractals, chaos,
complex systems, adaptation, source code, java, Mandelbrot, Julia set,
mathematics, logistic map, Henon map, strange attractor, dynamical
system, system theory, nature, cellular automata, boids, game theory,
prisoners dilemma, flocking, neural, neural network, genetic
algorithm, classifier system, evolution, learning"> <meta
name="robots" content="all, index, follow">
PAGETITLE
</head>

<body background="graphics/bg4.gif"
 link="#003366" alink="#000000" vlink="#000000"
 text="DARKBLUE">

<table bgcolor="DARKBLUE" border=0 cellspacing=0 cellpadding=1 width="100%" >
  <tr><td>
  <table bgcolor="OFFWHITE" border=0 cellspacing=0 cellpadding=10 width="100%" >
    <tr align=center valign=top>
      <td>
        <img alt="The Computational Beauty of Nature"
	 border=0 src="graphics/title3.gif" width="419" height="32">
	<br>
	<font color="#5555aa" face="Helvetica" size="+1"><b>
	Computer Explorations of Fractals, Chaos,<br>Complex Systems, and
	Adaptation
	</b></font>
      </td>
    </tr>
  </table>
  </td></tr>
</table>

<table width="100%" border=0 cellspacing=0 cellpadding=0>

<tr align=left valign=top><td width="LEFT_COL_WIDTH">
  <table border=0 cellspacing=0 cellpadding=0 width="LEFT_COL_WIDTH">

    <tr align=left valign=top><td>
      <img alt="" src="graphics/blank.gif" height="30">
    </td></tr>

    <tr align=left valign=top><td>

<script language="JavaScript">
function popUp(URL,NAME) {
amznwin=window.open(URL,NAME,'location=yes,scrollbars=yes,status=yes,toolbar=yes,resizable=yes,width=380,height=450,screenX=10,screenY=10,top=10,left=10');
amznwin.focus();}
document.open();
document.write("<a href=javascript:popUp('http://buybox.amazon.com/exec/obidos/redirect?tag=thecomputatbeaut&link_code=xsc&creative=23424&camp=2025&path=/dt/assoc/tg/aa/xml/assoc/-/0262561271/thecomputatbeaut/ref=ac_bb6_,_amazon')><img src=http://rcm-images.amazon.com/images/G/01/associates/remote-buy-box/buy6.gif border=0 alt='Buy from Amazon.com' ></a>");
document.close();
</script>
<noscript>
<form method="POST" action="http://buybox.amazon.com/o/dt/assoc/handle-buy-box=0262561271">
<input type="hidden" name="asin.0262561271" value="1">
<input type="hidden" name="tag-value" value="thecomputatbeaut">
<input type="hidden" name="tag_value" value="thecomputatbeaut">
<input type="image" name="submit.add-to-cart" value="Buy from Amazon.com" border="0" alt="Buy from Amazon.com" src="http://rcm-images.amazon.com/images/G/01/associates/add-to-cart.gif">
</form>
</noscript>
<br><br>


      <table border=0 cellspacing=0 cellpadding=1 bgcolor="DARKBLUE"
       width="100%">
        <tr><td>         
        <table border=0 cellspacing=0 cellpadding=2 bgcolor="TABLE_HEAD_COLOR"
         width="100%">
              <tr align=center><td>
	        <font MTITLEFONT><b>About the Book</b></font>
              </td></tr>
            </table>
          </td></tr>
        <tr><td>
        <table border=0 cellspacing=0 cellpadding=1 bgcolor="#eeeeee"
         width="100%">         
          <tr bgcolor="TOPTITLE_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR TOPTITLE_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    TOPTITLE_PRE
              <font COLUMN_FONT>
              <a href="index.html">title page</a>
              </font>
	    TOPTITLE_POST
            </td>
          </tr>
          <tr bgcolor="HOME_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR HOME_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    HOME_PRE
              <font COLUMN_FONT>
              <a href="home.html">home</a>NEWITEMMARKER
              </font>
	    HOME_POST
            </td>
          </tr>
          <tr bgcolor="COVER_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR COVER_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    COVER_PRE
              <font COLUMN_FONT>
              <a href="cover.html">cover artwork</a>
              </font>
	    COVER_POST
            </td>
          </tr>
          <tr bgcolor="BACK_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR BACK_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    BACK_PRE
              <font COLUMN_FONT>
              <a href="back.html">jacket text</a>
              </font>
	    BACK_POST
            </td>
          </tr>
          <tr bgcolor="TOC_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR TOC_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    TOC_PRE
              <font COLUMN_FONT>
              <a href="toc.html">table of contents</a>
              </font>
	    TOC_POST
            </td>
          </tr>
          <tr bgcolor="AUTHOR_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR AUTHOR_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    AUTHOR_PRE
              <font COLUMN_FONT>
              <a href="author.html">the author</a>NEWITEMMARKER
              </font>
	    AUTHOR_POST
            </td>
          </tr>
          <tr bgcolor="ORDERING_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR ORDERING_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    ORDERING_PRE
              <font COLUMN_FONT>
              <a href="ordering.html">ordering information</a>
              </font>
	    ORDERING_POST
            </td>
          </tr>
        </table>
      </td></tr></table>  
    </td></tr>

    <tr align=left valign=top><td>
      <img alt="" src="graphics/blank.gif" height="20">
    </td></tr>

    <tr align=left valign=top><td>

      <table border=0 cellspacing=0 cellpadding=1 bgcolor="DARKBLUE"
       width="100%">
        <tr><td>         
        <table border=0 cellspacing=0 cellpadding=2 bgcolor="TABLE_HEAD_COLOR"
         width="100%">
          <tr align=center><td>
            <font MTITLEFONT><b>Book Contents</b></font>
          </td></tr>
        </table>
        </td></tr>
        <tr><td>
        <table border=0 cellspacing=0 cellpadding=1 bgcolor="#eeeeee"
         width="100%">
          <tr bgcolor="THEMES_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR THEMES_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    THEMES_PRE
              <font COLUMN_FONT>
              <a href="themes.html">three themes</a>
              </font>
	    THEMES_POST
            </td>
          </tr>

          <tr bgcolor="PARTS_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR PARTS_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    PARTS_PRE
              <font COLUMN_FONT>
              <a href="parts.html">part synopses</a>
              </font>
	    PARTS_POST
            </td>
          </tr>
              
          <tr bgcolor="EXCERPTS_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR EXCERPTS_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    EXCERPTS_PRE
              <font COLUMN_FONT>
              <a href="excerpts0.html">selected excerpts</a>
              </font>
	    EXCERPTS_POST
            </td>
          </tr>

          <tr bgcolor="FIGURES_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR FIGURES_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    FIGURES_PRE
              <font COLUMN_FONT>
              <a href="fig.html">all figures from book</a>
              </font>
	    FIGURES_POST
            </td>
          </tr>

          <tr bgcolor="QUOTES_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR QUOTES_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    QUOTES_PRE
              <font COLUMN_FONT>
              <a href="quotes.html">quotes from book</a>
              </font>
	    QUOTES_POST
            </td>
          </tr>
          <tr bgcolor="GLOSSARY_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR GLOSSARY_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    GLOSSARY_PRE
              <font COLUMN_FONT>
              <a href="glossary-intro.html">glossary from book</a>
              </font>
	    GLOSSARY_POST
            </td>
          </tr>
          <tr bgcolor="BIBLIOGRAPHY_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR BIBLIOGRAPHY_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    BIBLIOGRAPHY_PRE
              <font COLUMN_FONT>
              <a href="bibliography.html">bibliography</a>
              </font>
	    BIBLIOGRAPHY_POST
            </td>
          </tr>
          <tr bgcolor="SLIDES_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR SLIDES_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    SLIDES_PRE
              <font COLUMN_FONT>
              <a href="slides.html"> slide show</a>
              </font>
	    SLIDES_POST
            </td>
          </tr>             
        </table>
      </td></tr></table>  
    </td></tr>


    <tr align=left valign=top><td>
      <img alt="" src="graphics/blank.gif" height="20">
    </td></tr>

    <tr align=left valign=top><td>

      <table border=0 cellspacing=0 cellpadding=1 bgcolor="DARKBLUE"
       width="100%">
        <tr><td>         
        <table border=0 cellspacing=0 cellpadding=2 bgcolor="TABLE_HEAD_COLOR"
         width="100%">
          <tr align=center><td>
            <font MTITLEFONT><b>Source Code</b></font>
          </td></tr>
        </table>
        </td></tr>
        <tr><td>
        <table border=0 cellspacing=0 cellpadding=1 bgcolor="#eeeeee"
         width="100%">

          <tr bgcolor="SOURCE_OPTS">
	  <td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR SOURCE_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    SOURCE_PRE
              <font COLUMN_FONT>
              <a href="source.html">overview &amp;<br>documentation</a>
              </font>
	    SOURCE_POST
            </td>
          </tr>
          <tr bgcolor="FAQ_OPTS">
	  <td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR FAQ_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    FAQ_PRE
              <font COLUMN_FONT>
              <a href="faq.html">FAQ list</a>NEWITEMMARKER
              </font>
	    FAQ_POST
            </td>
          </tr>

          <tr bgcolor="DOWNLOAD_OPTS">
	  <td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR DOWNLOAD_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    DOWNLOAD_PRE
              <font COLUMN_FONT>
              <a href="download.html">download source code</a>
              </font>
	    DOWNLOAD_POST
            </td>
          </tr>

          <tr bgcolor="JAVA_OPTS">
	  <td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR JAVA_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    JAVA_PRE
              <font COLUMN_FONT>
              <a href="java.html">java applets</a>
              </font>
	    JAVA_POST
            </td>
          </tr>
        </table>
      </td></tr></table>  
    </td></tr>

    <tr align=left valign=top><td>
      <img alt="" src="graphics/blank.gif" height="20">
    </td></tr>

    <tr align=left valign=top><td>

      <table border=0 cellspacing=0 cellpadding=1 bgcolor="DARKBLUE"
       width="100%">
        <tr><td>         
        <table border=0 cellspacing=0 cellpadding=2 bgcolor="TABLE_HEAD_COLOR"
         width="100%">
          <tr align=center><td>
            <font MTITLEFONT><b>Miscellany</b></font>
          </td></tr>
        </table>
        </td></tr>
        <tr><td>
        <table border=0 cellspacing=0 cellpadding=1 bgcolor="#eeeeee"
         width="100%">

          <tr bgcolor="NEWS_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR NEWS_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    NEWS_PRE
              <font COLUMN_FONT>
              <a href="news.html">news</a>NEWITEMMARKER
              </font>
	    NEWS_POST
            </td>
          </tr>

          <tr bgcolor="REVIEWS_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR REVIEWS_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    REVIEWS_PRE
              <font COLUMN_FONT>
              <a href="reviews.html">reviews &amp; awards</a>
              </font>
	    REVIEWS_POST
            </td>
          </tr>

          <tr bgcolor="ERRATA_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR ERRATA_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    ERRATA_PRE
              <font COLUMN_FONT>
              <a href="errata.html">errata</a>
              </font>
	    ERRATA_POST
            </td>
          </tr>
          <tr bgcolor="EDU_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR EDU_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    EDU_PRE
              <font COLUMN_FONT>
              <a href="edu.html">for educators</a>
              </font>
	    EDU_POST
            </td>
          </tr>
          <tr bgcolor="BIBTEX_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR BIBTEX_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    BIBTEX_PRE
              <font COLUMN_FONT>
              <a href="cbofn.bib">bibliography (BibTeX format)</a>
              </font>
	    BIBTEX_POST
            </td>
          </tr>
          <tr bgcolor="OTHER_OPTS"><td valign=top><b>&nbsp;&nbsp;&#183;</b></td>
#define HCOLOR OTHER_OPTS
	  <td onMouseover="this.style.backgroundColor='TABLE_HEAD_COLOR';"
              onMouseout="this.style.backgroundColor='HCOLOR';">
	    OTHER_PRE
              <font COLUMN_FONT>
              <a href="other.html">other links</a>
              </font>
	    OTHER_POST
#define HCOLOR OFFWHITE
            </td>
          </tr>
        </table>
      </td></tr></table>  
    </td></tr>



    <tr align=left valign=top><td>
      <img alt="" src="graphics/blank.gif" height="40">
    </td></tr>

    <tr valign=bottom align=left><td>

</td></tr>


  </table>
</td>

<td><table border=0 cellspacing=0 cellpadding=0 width="GAP_WIDTH">
<tr align=left valign=top><td>
<img alt="" src="graphics/blank.gif" width="GAP_WIDTH">
</td></tr></table></td>

<td width="100%">
  <table border=0 cellspacing=0 cellpadding=0 width="100%" >
    <tr align=left valign=top><td>
      <img alt="" src="graphics/blank.gif" height="30">
    </td></tr>
    <tr align=left valign=top>
      <td>
      TOPBAR

<font face="Helvetica" size="-1">


