#define TOPTITLE_OPTS OFFWHITE
#define HOME_OPTS OFFWHITE
#define COVER_OPTS OFFWHITE
#define BACK_OPTS OFFWHITE
#define TOC_OPTS OFFWHITE
#define AUTHOR_OPTS OFFWHITE
#define ORDERING_OPTS OFFWHITE

#define THEMES_OPTS OFFWHITE
#define PARTS_OPTS OFFWHITE
#define EXCERPTS_OPTS OFFWHITE
#define FIGURES_OPTS OFFWHITE
#define SLIDES_OPTS OFFWHITE

#define SOURCE_OPTS OFFWHITE
#define FAQ_OPTS OFFWHITE
#define DOWNLOAD_OPTS OFFWHITE
#define JAVA_OPTS OFFWHITE

#define NEWS_OPTS OFFWHITE
#define OLDNEWS_OPTS OFFWHITE
#define ERRATA_OPTS OFFWHITE
#define REVIEWS_OPTS OFFWHITE
#define EDU_OPTS OFFWHITE
#define QUOTES_OPTS OFFWHITE
#define GLOSSARY_OPTS OFFWHITE
#define BIBLIOGRAPHY_OPTS OFFWHITE
#define BIBTEX_OPTS OFFWHITE
#define OTHER_OPTS OFFWHITE


#define TOPTITLE_PRE HBEG
#define HOME_PRE HBEG
#define COVER_PRE HBEG
#define BACK_PRE HBEG
#define TOC_PRE HBEG
#define AUTHOR_PRE HBEG
#define ORDERING_PRE HBEG

#define THEMES_PRE HBEG
#define PARTS_PRE HBEG
#define EXCERPTS_PRE HBEG
#define FIGURES_PRE HBEG
#define SLIDES_PRE HBEG

#define SOURCE_PRE HBEG
#define FAQ_PRE HBEG
#define DOWNLOAD_PRE HBEG
#define JAVA_PRE HBEG

#define NEWS_PRE HBEG
#define OLDNEWS_PRE HBEG
#define ERRATA_PRE HBEG
#define REVIEWS_PRE HBEG
#define EDU_PRE HBEG
#define QUOTES_PRE HBEG
#define GLOSSARY_PRE HBEG
#define BIBLIOGRAPHY_PRE HBEG
#define BIBTEX_PRE HBEG
#define OTHER_PRE HBEG


#define TOPTITLE_POST HEND
#define HOME_POST HEND
#define COVER_POST HEND
#define BACK_POST HEND
#define TOC_POST HEND
#define AUTHOR_POST HEND
#define ORDERING_POST HEND

#define THEMES_POST HEND
#define PARTS_POST HEND
#define EXCERPTS_POST HEND
#define FIGURES_POST HEND
#define SLIDES_POST HEND

#define SOURCE_POST HEND
#define FAQ_POST HEND
#define DOWNLOAD_POST HEND
#define JAVA_POST HEND

#define NEWS_POST HEND
#define OLDNEWS_POST HEND
#define ERRATA_POST HEND
#define REVIEWS_POST HEND
#define EDU_POST HEND
#define QUOTES_POST HEND
#define GLOSSARY_POST HEND
#define BIBLIOGRAPHY_POST HEND
#define BIBTEX_POST HEND
#define OTHER_POST HEND


#define TABLE_HEAD_COLOR #bbbbdd
#define HIGHLIGHT_COLOR #ddddff

#define TITLE

#define TOPBAR <p><hr width="100%" size=2 noshade><font face="Helvetica" size="+2"><b>TITLE</b></font><br><hr width="100%" size=2 noshade><br></p><p>

#define TOPBAR <table border=0 cellspacing=0 cellpadding=1 bgcolor="DARKBLUE" width="100%"><tr><td><table border=0 cellspacing=0 cellpadding=5 width="100%" bgcolor="OFFWHITE"><tr><td><font face="Helvetica" size="+1"><b>TITLE</b></font></td></tr></table></td></tr></table><br><br>

#define BOXBEG <table border=0 cellspacing=1 cellpadding=0 bgcolor="#ffffff" width="100%"><tr><td><table border=0 cellspacing=0 cellpadding=1 bgcolor="DARKBLUE" width="100%"><tr><td><table border=0 cellspacing=0 cellpadding=5 width="100%" bgcolor="BLUE"><tr><td><font face="Helvetica" size=2>
#define BOXMID </font></td></tr></table></td></tr></table></td></tr><tr><td><table border=0 cellspacing=0 cellpadding=1 bgcolor="DARKBLUE" width="100%"><tr><td><table border=0 cellspacing=0 cellpadding=10 width="100%" bgcolor="OFFWHITE"><tr><td><font face="Helvetica" size=2>
#define BOXEND </font></td></tr></table></td></tr></table></td></tr></table>


#define MENUBEG <table border=0 cellspacing=1 cellpadding=0 bgcolor="#ffffff" width="100%"><tr><td><table border=0 cellspacing=0 cellpadding=1 bgcolor="DARKBLUE" width="100%"><tr><td><table border=0 cellspacing=0 cellpadding=2 width="100%" bgcolor="BLUE"><tr align=center><td><font face="Helvetica">
#define MENUMID </font></td></tr></table></td></tr></table></td></tr><tr><td><table border=0 cellspacing=0 cellpadding=1 bgcolor="DARKBLUE" width="100%"><tr><td><table border=0 cellspacing=0 cellpadding=0 width="100%" bgcolor="OFFWHITE"><tr><td><font face="Helvetica" size=2>
#define MENUEND </font></td></tr></table></td></tr></table></td></tr></table>

#define HCOLOR OFFWHITE
#define HBEG <ILAYER><LAYER onMouseover="this.bgColor='TABLE_HEAD_COLOR';" onMouseout="this.bgColor='HCOLOR';">

#define HEND </LAYER></ILAYER>




#define BOTTOMBAR </p><hr width="100%" size=1 noshade>
#define BOTTOMBAR

#define PAGETITLE <title>CBofN HYPHEN TITLE</title>

#define HYPHEN -
#define MODDATE 30 Nov 2002
#define NEWITEMMARKER <b>*</b>
#define TRACKER 
